export type Language = "en" | "es";

export const copy = {
  en: {
    skip: "Skip to content", menu: "Menu", close: "Close menu", language: "Change language",
    nav: ["Our Familia", "Events", "Our Roots", "Latin Niagara", "Find your place"],
    location: "Sponsored by NCSAC", heroLabel: "A CULTURAL COMMUNITY IN NIAGARA",
    heroTitle: ["NC LATIN", "CLUB"], heroText: "Where Cultures Bloom. More than a club. A place to belong. A little piece of Latin America, growing right here in Niagara.",
    heroAction: "Join us", heroSecondary: "Stay in the loop", instagramPending: "Instagram link coming soon", emailHint: "Opens your email app with a message ready to send", imageNote: "A world of many roots", scroll: "A little more magic, this way",
    ribbon: ["Many cultures", "Shared stories", "New connections", "A place for everyone"],
    familiaLabel: "01 / OUR FAMILIA", familiaTitle: ["Different roots.", "One familia."],
    familiaBody: "Some of us grew up with these cultures. Some are discovering them for the first time. All of us have a place here.",
    familiaSecond: "NC Latin Club is an independent cultural community in Niagara, Ontario. We’re here to celebrate Latin American cultures, share what makes us feel at home, and make room for new connections.",
    familiaQuote: ["Come as you are.", "Bring a little of home."], familiaNote: "CULTURE · CONNECTION · COMMUNITY",
    values: ["A story to share", "A rhythm to discover", "A seat at the table"],
    events: {
      label: "02 / EVENTS & GATHERINGS", title: ["Good moments.", "Better together."],
      body: "A place for the moments that bring us closer. Find our next gatherings here as they’re announced.",
      emptyLabel: "OUR NEXT CHAPTER", emptyTitle: "Something good is on the way.",
      emptyBody: "Our next events are coming soon. Once confirmed, you’ll find the date, place and how to join right here.",
      soon: "Coming soon", action: "Join us", date: "When", venue: "Where", registration: "Event registration",
    },
    rootsLabel: "03 / EXPLORE OUR ROOTS", rootsTitle: ["So many worlds.", "So much to discover."],
    rootsBody: "Latin America is more than one story. Follow your curiosity through the food, music, language and traditions that make each place its own.",
    choose: "Choose a country to begin", rootsNote: "An illustrated invitation to explore", countryKicker: "A LITTLE CURIOSITY GOES A LONG WAY",
    countryBody: "What does home sound like here? What’s on the table? Start with a question, and discover the stories behind the place.",
    countryTopics: ["Food & flavours", "Music & rhythm", "Stories & traditions"], countryFoot: "A first glimpse. More country stories to come.",
    niagaraLabel: "04 / DISCOVER LATIN NIAGARA", niagaraTitle: ["Latin soul.", "Local stories."],
    niagaraBody: "Culture doesn’t stop at a border. There are stories to discover closer to home, too. This is where our Niagara guide begins.",
    niagaraCategories: ["Food & flavours", "Music & gatherings", "Community & culture"],
    niagaraDetails: ["A future guide to Latin American flavours around Niagara. Places and public links will be added after verification.", "A space for confirmed cultural events and shared experiences. Dates and registration links will appear when announced.", "Discover local groups and cultural connections. Listings will be reviewed before being shared here."],
    niagaraCaption: "ROOTED IN NIAGARA, OPEN TO THE WORLD", niagaraNote: "Our local guide is growing. Verified places and events are on the way.",
    joinLabel: "THERE’S ROOM FOR YOU HERE", joinTitle: ["A little curiosity.", "A whole lot of familia."],
    joinBody: "Latin American or simply curious? You’re welcome here. Bring your stories, your questions, and yourself.",
    joinAction: "Join us", joinSecondary: "Stay in the loop", joinNote: "Opens your email app with a message ready to send.",
    footerLine: "Many roots. Growing together.", backTop: "Back to the sunshine", footerNote: "An independent cultural community in Niagara, Ontario.",
  },
  es: {
    skip: "Saltar al contenido", menu: "Menú", close: "Cerrar menú", language: "Cambiar idioma",
    nav: ["Nuestra Familia", "Eventos", "Nuestras Raíces", "Niagara Latino", "Encuentra tu lugar"],
    location: "Patrocinado por NCSAC", heroLabel: "UNA COMUNIDAD CULTURAL EN NIAGARA",
    heroTitle: ["NC LATIN", "CLUB"], heroText: "Donde las culturas florecen. Más que un club. Un lugar al que pertenecer. Un pedacito de Latinoamérica que crece aquí, en Niagara.",
    heroAction: "Únete", heroSecondary: "Síguenos en Instagram", instagramPending: "Pronto, el enlace de Instagram", emailHint: "Abre tu aplicación de correo con un mensaje listo para enviar", imageNote: "Un mundo de muchas raíces", scroll: "Un poco más de magia, por aquí",
    ribbon: ["Muchas culturas", "Historias compartidas", "Nuevas conexiones", "Un lugar para todos"],
    familiaLabel: "01 / NUESTRA FAMILIA", familiaTitle: ["Raíces diferentes.", "Una sola familia."],
    familiaBody: "Algunos crecimos con estas culturas. Otros las descubrimos por primera vez. Todos tenemos un lugar aquí.",
    familiaSecond: "NC Latin Club es una comunidad cultural independiente en Niagara, Ontario. Celebramos las culturas latinoamericanas, compartimos lo que nos hace sentir en casa y abrimos espacio a nuevas conexiones.",
    familiaQuote: ["Ven como eres.", "Trae un poquito de casa."], familiaNote: "CULTURA · CONEXIÓN · COMUNIDAD",
    values: ["Una historia que compartir", "Un ritmo por descubrir", "Un lugar en la mesa"],
    events: {
      label: "02 / EVENTOS Y ENCUENTROS", title: ["Buenos momentos.", "Mejor en familia."],
      body: "Un espacio para los momentos que nos acercan. Aquí encontrarás nuestros próximos encuentros cuando se anuncien.",
      emptyLabel: "NUESTRO PRÓXIMO CAPÍTULO", emptyTitle: "Algo bonito está por venir.",
      emptyBody: "Pronto habrá nuevos eventos. Cuando estén confirmados, aquí encontrarás la fecha, el lugar y cómo participar.",
      soon: "Próximamente", action: "Únete", date: "Cuándo", venue: "Dónde", registration: "Inscripción al evento",
    },
    rootsLabel: "03 / EXPLORA NUESTRAS RAÍCES", rootsTitle: ["Tantos mundos.", "Tanto por descubrir."],
    rootsBody: "Latinoamérica tiene más de una historia. Sigue tu curiosidad por los sabores, la música, las palabras y las tradiciones que hacen único a cada lugar.",
    choose: "Elige un país para comenzar", rootsNote: "Una invitación ilustrada a explorar", countryKicker: "LA CURIOSIDAD NOS LLEVA LEJOS",
    countryBody: "¿A qué suena el hogar aquí? ¿Qué hay en la mesa? Empieza con una pregunta y descubre las historias detrás del lugar.",
    countryTopics: ["Sabores", "Música y ritmo", "Historias y tradiciones"], countryFoot: "Una primera mirada. Pronto, más historias de cada país.",
    niagaraLabel: "04 / DESCUBRE NIAGARA LATINO", niagaraTitle: ["Alma latina.", "Historias locales."],
    niagaraBody: "La cultura no se detiene en una frontera. También hay historias por descubrir cerca de casa. Aquí comienza nuestra guía de Niagara.",
    niagaraCategories: ["Sabores", "Música y encuentros", "Comunidad y cultura"],
    niagaraDetails: ["Una futura guía de sabores latinoamericanos en Niagara. Añadiremos lugares y enlaces públicos después de verificarlos.", "Un espacio para eventos culturales confirmados y experiencias compartidas. Las fechas y los enlaces aparecerán cuando se anuncien.", "Descubre grupos locales y conexiones culturales. Revisaremos cada lugar antes de compartirlo aquí."],
    niagaraCaption: "CON RAÍCES EN NIAGARA Y ABIERTOS AL MUNDO", niagaraNote: "Nuestra guía local está creciendo. Pronto habrá lugares y eventos verificados.",
    joinLabel: "AQUÍ HAY UN LUGAR PARA TI", joinTitle: ["Un poco de curiosidad.", "Muchísima familia."],
    joinBody: "¿Eres latinoamericano o simplemente tienes curiosidad? Aquí eres bienvenido. Trae tus historias, tus preguntas y tus ganas de compartir.",
    joinAction: "Únete", joinSecondary: "Síguenos en Instagram", joinNote: "Abre tu aplicación de correo con un mensaje listo para enviar.",
    footerLine: "Muchas raíces. Creciendo juntos.", backTop: "Volver al inicio", footerNote: "Una comunidad cultural independiente en Niagara, Ontario.",
  },
} as const;

export const countries = [
  { id: "mexico", name: { en: "Mexico", es: "México" }, display: "México", x: 28, y: 24, color: "#d49a63" },
  { id: "colombia", name: { en: "Colombia", es: "Colombia" }, display: "Colombia", x: 59, y: 49, color: "#d4aa48" },
  { id: "peru", name: { en: "Peru", es: "Perú" }, display: "Perú", x: 55, y: 61, color: "#db997e" },
  { id: "brazil", name: { en: "Brazil", es: "Brasil" }, display: "Brasil", x: 70, y: 62, color: "#b1bf8b" },
] as const;
