// Requires a fresh running app and Chromium CDP (default port 9222).
const base=process.env.CHECK_URL || 'http://localhost:3022';
const page=await(await fetch('http://127.0.0.1:9222/json/new?about:blank',{method:'PUT'})).json();const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map(),errors=[],failures=[];
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p.reject(m.error);else p.resolve(m.result)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)});
const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))});
const evalJS=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const pause=ms=>new Promise(r=>setTimeout(r,ms));const check=(name,ok)=>{console.log(name,ok);if(!ok)failures.push(name)};async function wait(expr){for(let i=0;i<100;i++){if(await evalJS(`Boolean(${expr})`))return;await pause(60)}throw Error(expr)}
await send('Page.enable');await send('Runtime.enable');await send('Emulation.setDeviceMetricsOverride',{width:375,height:920,deviceScaleFactor:1,mobile:true});await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await send('Page.navigate',{url:base+'/niagara'});await wait('document.querySelectorAll(".leaflet-marker-icon").length===15');await evalJS('document.querySelector("article[data-place=sombra] > button").scrollIntoView({block:"center"});document.querySelector("article[data-place=sombra] > button").focus();document.querySelector("article[data-place=sombra] > button").click()');await wait('document.querySelector("[data-selected=sombra]")');await pause(200);
check('opened last-card detail is visible on mobile',await evalJS('(()=>{const r=document.querySelector("[data-selected=sombra]").getBoundingClientRect();return r.top>=0 && r.top<innerHeight && r.bottom>0})()'));
check('selection announced and connected to trigger',await evalJS('document.querySelector("article[data-place=sombra] > button").getAttribute("aria-controls")==="detail-sombra" && [...document.querySelectorAll("[role=status]")].some(p=>p.textContent.includes("Sombra"))'));
check('card activation preserves trigger focus',await evalJS('document.activeElement===document.querySelector("article[data-place=sombra] > button")'));
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Tab',code:'Tab',windowsVirtualKeyCode:9});await pause(100);check('next Tab reaches opened detail',await evalJS('!!document.activeElement.closest("[data-selected=sombra]")'));
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await wait('!document.querySelector("[data-selected]")');check('Escape returns focus to card',await evalJS('document.activeElement===document.querySelector("[data-place=sombra] h2 button")'));
await evalJS('document.querySelector(".leaflet-marker-icon[title*=CoCo]").click()');await wait('document.querySelector("[data-selected=coco-bar-mexican-grill]")');await pause(150);check('map selection reveals accessible detail heading',await evalJS('document.activeElement.id==="selected-place-title" && document.querySelector("[data-selected]").getBoundingClientRect().top>=0 && document.querySelector("[data-selected]").getBoundingClientRect().top<innerHeight'));
check('no runtime exceptions',errors.length===0);ws.close();await fetch('http://127.0.0.1:9222/json/close/'+page.id);if(failures.length)throw Error(failures.join('; '));console.log('PASS Niagara detail reveal');
