export const eventsCopy = {
  en: {
    eyebrow: 'THE LATIN AGENDA', title: ['Make plans.', 'Make memories.'], body: 'Campus connections. Local discoveries. Dates that bring our cultures to life. Find your next moment here.',
    categories: { 'at-nc': 'At NC', 'out-of-nc': 'Out of NC', 'latin-dates': 'Latin dates' },
    intros: { 'at-nc': 'Meet up, dance and connect through events at Niagara College.', 'out-of-nc': 'Discover Latin music, culture and community in Niagara, with selected festivals in Burlington and Toronto.', 'latin-dates': 'Celebrations and traditions from across Latin America. Cultural dates, each with its own story.' },
    emptyTitles: { 'at-nc': 'The next gathering is on its way.', 'out-of-nc': 'More Latin Niagara is on the way.', 'latin-dates': 'Our cultural calendar is growing.' },
    emptyBodies: { 'at-nc': 'Confirmed gatherings will appear here with dates and registration details.', 'out-of-nc': 'Browse the calendar or past editions. Know another event? Tell us about it.', 'latin-dates': 'Browse another date or the archive to discover more traditions. These cultural references do not establish days off in Ontario.' },
    list: 'List', calendar: 'Calendar', upcoming: 'Upcoming', past: 'Past', loading: 'Loading the agenda…', suggest: 'Suggest an event', noPast: 'No past activities published yet.', noDay: 'No activities published for this day.', dayHint: 'Choose a day to discover what’s happening.', today: 'Today', previousMonth: 'Previous month', nextMonth: 'Next month', activity: 'activity', activities: 'activities', on: 'On',
    when: 'When', until: 'Until', where: 'Where', organizer: 'Organized by', admission: 'Tickets & guests', scope: 'Country / culture', fullDay: 'All day', zone: 'All event times are shown in Niagara time.', source: 'Original source', reviewed: 'Information reviewed', sourceCapture: 'Details supplied by club leadership from the original listing.', register: 'Register with the organizer', external: 'Opens in a new tab', back: 'Back to the agenda', explore: 'See the details', viewAgenda: 'Explore the full agenda', cancelled: 'Cancelled', rescheduled: 'Rescheduled', cultural: 'A cultural date — discover its story.',
    gallery: 'Event images', image: 'Image', previousImage: 'Previous image', nextImage: 'Next image', viewImage: 'View image', imageUnavailable: 'This image is unavailable.',
  },
  es: {
    eyebrow: 'LA AGENDA LATINA', title: ['Haz planes.', 'Crea recuerdos.'], body: 'Encuentros en el campus. Descubrimientos locales. Fechas que dan vida a nuestras culturas. Encuentra aquí tu próximo momento.',
    categories: { 'at-nc': 'En NC', 'out-of-nc': 'Fuera de NC', 'latin-dates': 'Fechas latinas' },
    intros: { 'at-nc': 'Encuéntrate, baila y conecta a través de los eventos de Niagara College.', 'out-of-nc': 'Descubre música, cultura y comunidad latina en Niagara, con festivales seleccionados en Burlington y Toronto.', 'latin-dates': 'Celebraciones y tradiciones de Latinoamérica. Fechas culturales, cada una con su propia historia.' },
    emptyTitles: { 'at-nc': 'El próximo encuentro está en camino.', 'out-of-nc': 'Pronto, más Niagara latino.', 'latin-dates': 'Nuestro calendario cultural está creciendo.' },
    emptyBodies: { 'at-nc': 'Los encuentros confirmados aparecerán aquí con sus fechas y detalles de inscripción.', 'out-of-nc': 'Explora el calendario o las ediciones anteriores. ¿Conoces otro evento? Cuéntanos.', 'latin-dates': 'Explora otra fecha o el archivo para descubrir más tradiciones. Estas referencias culturales no implican días libres en Ontario.' },
    list: 'Lista', calendar: 'Calendario', upcoming: 'Próximos', past: 'Anteriores', loading: 'Cargando la agenda…', suggest: 'Sugiere un evento', noPast: 'Todavía no hay actividades anteriores publicadas.', noDay: 'No hay actividades publicadas para este día.', dayHint: 'Elige un día para descubrir qué está pasando.', today: 'Hoy', previousMonth: 'Mes anterior', nextMonth: 'Mes siguiente', activity: 'actividad', activities: 'actividades', on: 'El',
    when: 'Cuándo', until: 'Hasta', where: 'Dónde', organizer: 'Organiza', admission: 'Entradas e invitados', scope: 'País / cultura', fullDay: 'Todo el día', zone: 'Todos los horarios de eventos se muestran en la hora de Niagara.', source: 'Fuente original', reviewed: 'Información revisada', sourceCapture: 'Detalles aportados por los responsables del club desde la publicación original.', register: 'Inscríbete con el organizador', external: 'Abre en una pestaña nueva', back: 'Volver a la agenda', explore: 'Ver los detalles', viewAgenda: 'Explora la agenda completa', cancelled: 'Cancelado', rescheduled: 'Reprogramado', cultural: 'Una fecha cultural: descubre su historia.',
    gallery: 'Imágenes del evento', image: 'Imagen', previousImage: 'Imagen anterior', nextImage: 'Imagen siguiente', viewImage: 'Ver imagen', imageUnavailable: 'Esta imagen no está disponible.',
  },
} as const;
