import type { Language } from '../home-copy';
export type LocalizedText = Record<Language, string>;
export type CalendarDate = string;
export type CalendarMonth = string;
export type AgendaCategory = 'at-nc' | 'out-of-nc' | 'latin-dates';
export type EntryImage = { src: string; width: number; height: number; alt: LocalizedText; caption?: LocalizedText };
export type EditorialSource = { url: string; reviewedOn: CalendarDate; provenance: 'user-capture' | 'official-page' };
type EntryBase = { id: string; slug: string; title: LocalizedText; description: LocalizedText; source: EditorialSource; images?: readonly EntryImage[]; links?: readonly { url: string; label: LocalizedText }[]; note?: LocalizedText };
export type EventSession = { startsAt: string; endsAt?: string; title?: LocalizedText; registrationUrl?: string };
export type EventEntry = EntryBase & { kind: 'event'; category: 'at-nc' | 'out-of-nc'; venue: LocalizedText; city?: LocalizedText; address?: string; organizer: LocalizedText; admission?: LocalizedText; registrationUrl?: string; status: 'scheduled' | 'cancelled' | 'rescheduled'; statusNote?: LocalizedText; sessions?: readonly EventSession[] } & ({ startsAt: string; endsAt?: string; dateSpan?: never } | { dateSpan: { start: CalendarDate; end: CalendarDate }; startsAt?: never; endsAt?: never });
export type CulturalEntry = EntryBase & { kind: 'cultural-date'; category: 'latin-dates'; date: CalendarDate; endDate?: CalendarDate; calendarDisplay?: 'month'; scope: LocalizedText };
export type AgendaEntry = EventEntry | CulturalEntry;
export type AgendaState = { categories: AgendaCategory[]; view: 'list' | 'calendar'; period: 'upcoming' | 'past'; month: CalendarMonth; selectedDate: CalendarDate };
